export const GET_LIST_USERS_BEGIN = "GET_LIST_USERS_BEGIN"
export const GET_LIST_USERS_SUCCESS = "GET_LIST_USERS_SUCCESS"
export const GET_LIST_USERS_FAILURE = "GET_LIST_USERS_FAILURE"

export const IMPORT_STOCKS_SUCCESS = "IMPORT_STOCKS_SUCCESS"
export const IMPORT_CHECKLISTS_SUCCESS = "IMPORT_CHECKLISTS_SUCCESS"
export const IMPORT_CHECKLIST_ITEMS_SUCCESS = "IMPORT_CHECKLIST_ITEMS_SUCCESS"
export const IMPORT_USERS_SUCCESS = "IMPORT_USERS_SUCCESS"
export const IMPORT_SHOPS_SUCCESS = "IMPORT_SHOPS_SUCCESS"

export const EDIT_USER_BEGIN = "EDIT_USER_BEGIN"
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS"
export const EDIT_USER_FAILURE = "EDIT_USER_FAILURE"

export const GET_LIST_CHECKIN_CHECKOUT_SUCCESS = "GET_LIST_CHECKIN_CHECKOUT_SUCCESS"
